toys = 10
print(toys == 1)
print(toys > 1)
print(toys < 1)
print(toys != 1)
print(toys <= 10)
print(not toys <= 1)
print(toys == 1)
print(toys == 9 or toys == 10)
print(toys == 9 or toys == 10)