name1=input()
name2=input()
surname1=input()
surname2=input()
phone1=input()
phone2=input()
print("Имя:", end="")
print(name1, end="")
print(", Фамилия:", end="")
print(surname1, end="")
print(", Телефон:", end="")
print(phone1)
print("Имя:", end="")
print(name2, end="")
print(", Фамилия:", end="")
print(surname2,end="")
print(", Телефон:", end="")
print(phone2)