name = input()
namea = input()
surname = input()
surnamea = input()
phone = input()
phonea = input()
print("Имя:", end="")
print(name, end="")
print(", Фамилия:", end="")
print(surname, end="")
print(", Телефон:", end="")
print(phone)
print("Имя:", end="")
print(namea, end="")
print(", Фамилия:", end="")
print(surnamea, end="")
print(", Телефон:", end="")
print(phonea, end="")
