print("введите 1 число")
n = input()
print("введите 2 число")
m = input()
print(n[1])
print(m[2])
d = int(m[2]) + int(n[1])
print(d)
print(n[3])
print(m[0])
f = int(n[3]) * int(m[0])
print(f)
