n1 = input()
n2 = input()
s1 = input()
s2 = input()
p1 = input()
p2 = input()
print('Имя:' , end="")
print(n1, end="")
print(', Фамилия:', end="")
print(s1, end="")
print(', Телефон:' ,  end="")
print(p1)
print('Имя:' , end="")
print(n2, end="")
print(', Фамилия:', end="")
print(s2, end="")
print(', Телефон:' ,  end="")
print(p2)