print("введите первое число:")
a = int(input())
print("введите второе число:")
b = int(input())
print("введите третье число:")
c = int(input())
print("введите четвертое число:")
d = int(input())
e = (a - b + d) *c
print("ваш результат равен")
print(e)