print("Введите первое число")
a = int(input())
print("Введите второе число")
b = int(input())
print("Ввудите третье число")
c = int(input())
print("Ввудите четвёртое число")
d = int(input())
e = (a-b)*c + d
print("Результат равен")
print(e)