print('Введите четырехзначное число')
a = input()
print('Введите трехзначное число')
g = input()
e = int(a[3]) + int(g[0])
print('Итог сложение')
print(e)
f = int(a[1]) * int(g[2])
print('Итог умножения')
print(f)